Title =  "42Vision"
LanguageCode = "zh-CN"
BaseUrl = "http://42vision.github.io"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
PygmentsUseClasses = true
DefaultContentLanguage = "zh"

[Params]
  Introduce = "Developer & RabbitLover"
  Description = "42Vision | 博客 | 开源 | 创业 | 想法 | 笔记"
  Keywords =  "42Vision,博客,独立,博客,开发者,开源,思考,笔记,技术,分享,权利的游戏"
  Subtitle = "谁落在虫洞中央, 看见消失的光"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  #BaiduStatsId = "0b07433b4ab8d587dae7d34e71973839"
  # QQStatsId = "58416275"
  Fancybox = true

[Author]
  Name = "字节熊"

[Params.Share]
  #DuoShuo = "lanlingzi"
  Baidu = true

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "技术"
  Pre = "code"
  URL = "/categories/技术/"
  Weight = 2
[[Menu.Main]]
  Name = "感想"
  Pre = "tint"
  URL = "/categories/感想/"
  Weight = 3
[[Menu.Main]]
  Name = "笔记"
  Pre = "book"
  URL = "/categories/笔记/"
  Weight = 4
[[Menu.Main]]
  Name = "杂记"
  Pre = "leaf"
  URL = "/categories/杂记/"
  Weight = 5
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 6
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 7

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/sharkspeed"

[[Params.Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/gitbear"
